[platformio]
default_envs = crowpanel
[env:crowpanel]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.20
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 8MB
board_build.psram = enabled
monitor_speed = 115200
build_flags = -std=gnu++17 -Wall -Wextra -Werror -I core/include
build_src_filter = +<*> +<../core/src/*.cpp>
